// Ciudades de Colombia para el selector de "Datos de la tienda" (formato
// "Ciudad, Departamento"). Incluye capitales de departamento y los
// municipios con mayor población o presencia comercial. No es exhaustiva:
// el campo permite escribir cualquier otra ciudad a mano.

export const CIUDADES_COLOMBIA: string[] = [
  // Bogotá y Cundinamarca
  "Bogotá, D.C.",
  "Soacha, Cundinamarca",
  "Chía, Cundinamarca",
  "Zipaquirá, Cundinamarca",
  "Facatativá, Cundinamarca",
  "Fusagasugá, Cundinamarca",
  "Girardot, Cundinamarca",
  "Mosquera, Cundinamarca",
  "Madrid, Cundinamarca",
  "Funza, Cundinamarca",
  "Cajicá, Cundinamarca",
  "Sopó, Cundinamarca",
  "La Calera, Cundinamarca",
  "Cota, Cundinamarca",
  "Tocancipá, Cundinamarca",
  "Villeta, Cundinamarca",
  // Antioquia
  "Medellín, Antioquia",
  "Bello, Antioquia",
  "Itagüí, Antioquia",
  "Envigado, Antioquia",
  "Sabaneta, Antioquia",
  "La Estrella, Antioquia",
  "Rionegro, Antioquia",
  "Apartadó, Antioquia",
  "Turbo, Antioquia",
  "Caucasia, Antioquia",
  "Copacabana, Antioquia",
  "Marinilla, Antioquia",
  "Santa Fe de Antioquia, Antioquia",
  // Valle del Cauca
  "Cali, Valle del Cauca",
  "Palmira, Valle del Cauca",
  "Buenaventura, Valle del Cauca",
  "Tuluá, Valle del Cauca",
  "Cartago, Valle del Cauca",
  "Buga, Valle del Cauca",
  "Jamundí, Valle del Cauca",
  "Yumbo, Valle del Cauca",
  // Atlántico
  "Barranquilla, Atlántico",
  "Soledad, Atlántico",
  "Malambo, Atlántico",
  "Sabanalarga, Atlántico",
  "Puerto Colombia, Atlántico",
  // Bolívar
  "Cartagena, Bolívar",
  "Magangué, Bolívar",
  "Turbaco, Bolívar",
  "El Carmen de Bolívar, Bolívar",
  // Santander
  "Bucaramanga, Santander",
  "Floridablanca, Santander",
  "Girón, Santander",
  "Piedecuesta, Santander",
  "Barrancabermeja, Santander",
  "San Gil, Santander",
  "Socorro, Santander",
  // Norte de Santander
  "Cúcuta, Norte de Santander",
  "Ocaña, Norte de Santander",
  "Pamplona, Norte de Santander",
  "Villa del Rosario, Norte de Santander",
  // Boyacá
  "Tunja, Boyacá",
  "Duitama, Boyacá",
  "Sogamoso, Boyacá",
  "Chiquinquirá, Boyacá",
  "Paipa, Boyacá",
  // Eje Cafetero
  "Manizales, Caldas",
  "La Dorada, Caldas",
  "Pereira, Risaralda",
  "Dosquebradas, Risaralda",
  "Armenia, Quindío",
  "Calarcá, Quindío",
  // Tolima y Huila
  "Ibagué, Tolima",
  "Espinal, Tolima",
  "Melgar, Tolima",
  "Chaparral, Tolima",
  "Neiva, Huila",
  "Pitalito, Huila",
  "Garzón, Huila",
  "La Plata, Huila",
  // Meta, Casanare y Llanos
  "Villavicencio, Meta",
  "Acacías, Meta",
  "Granada, Meta",
  "Yopal, Casanare",
  "Arauca, Arauca",
  "Puerto Carreño, Vichada",
  "Inírida, Guainía",
  "San José del Guaviare, Guaviare",
  "Mitú, Vaupés",
  // Amazonía
  "Florencia, Caquetá",
  "Mocoa, Putumayo",
  "Puerto Asís, Putumayo",
  "Leticia, Amazonas",
  // Costa Caribe
  "Santa Marta, Magdalena",
  "Ciénaga, Magdalena",
  "Fundación, Magdalena",
  "Valledupar, Cesar",
  "Aguachica, Cesar",
  "Riohacha, La Guajira",
  "Maicao, La Guajira",
  "Uribia, La Guajira",
  "Montería, Córdoba",
  "Lorica, Córdoba",
  "Cereté, Córdoba",
  "Sincelejo, Sucre",
  "Corozal, Sucre",
  // Pacífico
  "Quibdó, Chocó",
  "Popayán, Cauca",
  "Santander de Quilichao, Cauca",
  "Pasto, Nariño",
  "Ipiales, Nariño",
  "Tumaco, Nariño",
  // Islas
  "San Andrés, San Andrés y Providencia",
];
